adds protocol support for `redis` and `rediss`
valkey-io/valkey-py pull request #27
Opened 2024-06-27 17:02 UTC by kjaymiller

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Do tests and lints pass with this change?
- [X] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [X] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [ ] Is there an example added to the examples folder (if applicable)?
- [X] Was the change added to CHANGES file?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

- Adds 'redis://' and 'rediss://' to the list of accepted protocols for both sync and async connection pools
- Updates tests to use parameterization so that tests for valkey:// and valkeys:// also test redis// and rediss://

2024-06-28 09:00 UTC, aiven-sal requested changes
Thanks for the PR!
I have a couple of requests:
1) could you squash the lint changes in your second commit in the first one? It would make it easier for me to review commit-by-commit.
2) ignore the CHANGES file, it wasn't really used much recently and we have a nice bot that can summarize changes in releases from PRs. It isn't perfect, but for now let's just use that.

2024-06-28 09:00 UTC, aiven-sal commented on valkey/asyncio/connection.py
> +    valid_schemes = (
This check shouldn't be here and, in fact, it should be removed from the other `parse_url` as well. Schemes in URIs should not be case sensitive (cfr. [RFC3986 Section 3.1](https://datatracker.ietf.org/doc/html/rfc3986#section-3.1))

2024-06-28 11:49 UTC, kjaymiller commented on valkey/asyncio/connection.py
> +    valid_schemes = (
@aiven-sal - regarding raising that error, should a similar check be done to the `ParseResult.scheme` which would return the protocol in all lowercase.

```py
# an example
>>> url =urlparse("HTTPX://foo.com:900")
>>> url
ParseResult(scheme='httpx', netloc='foo.com:900', path='', params='', query='', fragment='')
```

2024-06-28 11:56 UTC, aiven-sal commented on valkey/asyncio/connection.py
> +    valid_schemes = (
I think you can just leave the check as it was before (adding redis/rediss of course) with the exception raised in the `else`, so that we know for sure that what we check is what we use and we don't end up with 2 different places to maintain/update with the supported schemas.

2024-06-28 12:09 UTC, kjaymiller commented on tests/test_connection_pool.py
> +
These tests (and their async component) would need to be removed as there is no check at this point.

```suggestion
```

2024-06-28 12:13 UTC, kjaymiller commented on valkey/asyncio/connection.py
> +    valid_schemes = (
@aiven-sal - I agree however the sync version wasn't checking in that manner. Should I apply the same check to the sync version?

2024-06-28 12:16 UTC, aiven-sal commented on valkey/asyncio/connection.py
> +    valid_schemes = (
That can be done in a different PR (or maybe not needed at all if we unify the two parse_url).
Let's jut focus on adding redis/rediss.

2024-06-28 12:51 UTC, kjaymiller commented
> 1. could you squash the lint changes in your second commit in the first one? It would make it easier for me to review commit-by-commit.

I hope I did this correctly

2024-06-28 12:52 UTC, kjaymiller commented on valkey/asyncio/connection.py
> +    valid_schemes = (
I've added back the original test at the end and removed the check in sync (and it's test since there is no check on sync still)

2024-07-03 12:42 UTC, kjaymiller commented
@aiven-sal - Is there something on my end holding progress on this?

2024-07-03 15:12 UTC, aiven-sal commented
> @aiven-sal - Is there something on my end holding progress on this?

Nope, there is some related work going on in https://github.com/valkey-io/valkey-py/pull/29, so I'm waiting for it to get merged. Then this will need to be rebased (I'm sorry for the inconvenience).

2024-07-03 16:26 UTC, aiven-sal commented
So #29 was merged. It should handle #23 and #25 . 
This PR also contains the fix for #26.
To keep things tidier I'll close this PR, so you can open another one just for the #26 fix.
Thanks again and sorry for the delay. It was just easier to fix #23 and #25 together.

2024-07-03 16:26 UTC, closed without merging