adds isclose checks to flaky geotests
valkey-io/valkey-py pull request #61
Opened 2024-07-31 19:30 UTC by kjaymiller

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [X] Do tests and lints pass with this change?
- [X] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [X] Is the new or changed code fully tested?
- [NA] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?
- [NA] Is there an example added to the examples folder (if applicable)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

- add geochecks to conftest
- uses isclose to check float values
- renamed check to assert_geo_is_close
- update_assert_is_geo_tests
- format with black

2024-08-05 08:20 UTC, aiven-sal commented
Hi Jay! Thanks for the PR.
I don't know if you noticed, but there are some issues with this PR:
https://github.com/valkey-io/valkey-py/actions/runs/10186469705/job/28210444146?pr=61#step:4:125
You should also re-base it to pick up the latest changes.

2024-08-06 08:45 UTC, aiven-sal requested changes
Hi! Thanks for fixing the linters.
Could you squash/fixup all of you commits in the first one?

Otherwise the PR looks great!

2024-08-06 08:45 UTC, aiven-sal commented on tests/conftest.py
> +        assert math.isclose(*i)
There is no need to force the conversion to list here.
You could do something like:
```suggestion
    for a, b in zip(coords, expected_coords):
        assert math.isclose(a, b)
```

2024-08-06 08:45 UTC, aiven-sal commented on tests/test_asyncio/test_commands.py
> +        if "withcoord" in georadius_kwargs:
I'd also add a check on `georadius_result` lenght e.g.
```suggestion
        assert len(georadius_result) == 1
        if "withcoord" in georadius_kwargs:
```

2024-08-06 08:45 UTC, aiven-sal commented on tests/test_commands.py
> +            b"place2",
Why is this change needed? Do we know why the value was originally that?

2024-08-06 08:45 UTC, aiven-sal commented on tests/test_commands.py
> +        )
As above e.g.
```suggestion
        )
        assert len(geosearch_result) == 1
```

2024-08-06 08:45 UTC, aiven-sal commented on tests/test_commands.py
> +        if "withcoord" in georadius_kwargs:
As above e.g.
```suggestion
        assert len(georadius_result) == 1
        if "withcoord" in georadius_kwargs:
```

2024-08-06 08:45 UTC, aiven-sal commented on tests/test_commands.py
> -            b"\x80place2",
Same question as above.

2024-08-06 08:45 UTC, aiven-sal commented on tests/test_commands.py
> +        # for radius place 1 and 2 everything but the coordinates should be the same
I'm not sure I understand this comment.
What do you mean by "everything [...] should be the same" ? All values between place1 and place2 look different for me.

2024-08-06 13:12 UTC, kjaymiller commented on tests/test_commands.py
> +            b"place2",
it can be reverted... there were some that were \x80 and others that weren't

2024-08-06 13:25 UTC, kjaymiller commented on tests/test_commands.py
> +        # for radius place 1 and 2 everything but the coordinates should be the same
It was meant to say that you can check for "==" as the information should be the exact values.

I can remove this..

2024-08-06 13:25 UTC, kjaymiller commented on tests/test_commands.py
> +        # for radius place 1 and 2 everything but the coordinates should be the same
```suggestion
```

2024-08-06 13:26 UTC, kjaymiller commented on tests/test_commands.py
> +            b"place2",
```suggestion
            b"x80place2",
```

2024-08-06 13:33 UTC, kjaymiller commented on tests/test_commands.py
> +            b"place2",
```suggestion
            b"\x80place2",
```

2024-08-06 19:37 UTC, kjaymiller commented on tests/test_asyncio/test_commands.py
> +        test_str = b"\xaa\x00\xff\x55"
```suggestion
        test_str = b"\xAA\x00\xFF\x55"
```

2024-08-06 19:37 UTC, kjaymiller commented on tests/test_asyncio/test_commands.py
> +        test_str = b"\xaa\x00\xff\x55"
```suggestion
        test_str = b"\xAA\x00\xFF\x55"
```

2024-08-06 19:39 UTC, kjaymiller commented on tests/test_asyncio/test_commands.py
> +        await r.set("b", b"\x01\x02\xff")
```suggestion
        await r.set("a", b"\x01\x02\xFF\xFF")
        await r.set("b", b"\x01\x02\xFF")
```

2024-08-06 19:40 UTC, kjaymiller commented on tests/test_commands.py
> +        test_str = b"\xaa\x00\xff\x55"
```suggestion
        test_str = b"\xAA\x00\xFF\x55"
```

2024-08-06 19:40 UTC, kjaymiller commented on tests/test_commands.py
> +        test_str = b"\xaa\x00\xff\x55"
```suggestion
        test_str = b"\xAA\x00\xFF\x55"
```

2024-08-06 19:40 UTC, kjaymiller commented on tests/test_commands.py
> +        test_str = b"\x01\x02\xff"
test_str = b"\x01\x02\xFF"

2024-08-06 19:41 UTC, kjaymiller commented on tests/test_commands.py
> +        test_str = b"\x01\x02\xff"
```suggestion
        test_str = b"\x01\x02\xFF"
```

2024-08-06 19:41 UTC, kjaymiller commented on tests/test_commands.py
> +            r"^{0}\.hmset\(\) is deprecated\. " r"Use {0}\.hset\(\) instead\.$".format(
```suggestion
            r"^{0}\.hmset\(\) is deprecated\. " 
            r"Use {0}\.hset\(\) instead\.$".format(
```

2024-08-06 19:42 UTC, kjaymiller commented on tests/test_commands.py
> +            r"^{0}\.hmset\(\) is deprecated\. " r"Use {0}\.hset\(\) instead\.$".format(
```suggestion
            r"^{0}\.hmset\(\) is deprecated\. " 
            r"Use {0}\.hset\(\) instead\.$".format(
```

2024-08-06 19:42 UTC, kjaymiller commented on tests/test_commands.py
> +            b"place2",
```suggestion
            b"\x80place2",
```

2024-08-06 20:13 UTC, kjaymiller commented on tests/test_commands.py
> -            b"\x80place2",
I've put them back. I'm a little worried about this being there with no explanation. If you're testing if you can use characters outside of the ascii range I feel it should be it's own test (which we have tests that do that already).

I think more likely it was a character insertion from a non-ascii keyboard. Note to self to run a git blame on it

2024-08-06 20:28 UTC, kjaymiller commented on tests/test_asyncio/test_commands.py
> +        test_str = b"\xaa\x00\xff\x55"
@aiven-sal - ai apologize on this one. Apparently I have a linter that lowercases these values. seems to correct it when I save. This was another issue I had elsewhere. 

I did verify there is no difference between `\xaa` and `\xAA' in python. same for the `\xff`

2024-08-07 08:14 UTC, aiven-sal commented on tests/test_asyncio/test_commands.py
> +        test_str = b"\xaa\x00\xff\x55"
It's okay

2024-08-07 08:18 UTC, aiven-sal commented on tests/test_asyncio/test_commands.py
> +        test_str = b"\x01\x02\xff"
```suggestion
        test_str = b"\x01\x02\xFF"
```

2024-08-07 09:03 UTC, aiven-sal approved these changes
Thanks!

2024-08-07 10:16 UTC, ahmedsobeh approved these changes

2024-08-07 10:16 UTC, merged